os:
    - linux
language: node_js
install:
    - npm ci
node_js:
    - '10'
cache:
    directories:
        - node_modules
        - '$HOME/.npm'
addons:
    sauce_connect: true
script:
    - echo '1. Browserstack tests'
    - npm run test.remote
